### ISSUE TITLE
Document mappings between source files and OWL

### ISSUE THREAD

**Issue by cmungall** [obophenotype/vccf-ontology#13]
Example

The source has ForBranchesSee

https://github.com/hubmapconsortium/hra-vccf/blob/d9214eea16009264f0423d29845966d77a8925ac/HRA-VCCF_CreateTables.sql#L24

This is not documented in the source repo

But is documented here
https://www.nature.com/articles/s41597-023-02018-0

How do we translate this? Does this get dropped?

**Comment by anitacaron** [comment]
How should it be translated? In the first draft, we used minimal information from the data source.

**Comment by anitacaron** [comment]
From the paper:

ForBranchesSee. For some vessels, like the left and right renal arteries, rather than showing all the branches of both arteries, a “virtual” merged vessel is created (e.g., just “renal artery”). The branches are only added once to that virtual vessel. This field indicates the name of the virtual vessel that has the branches.

**Comment by anitacaron** [comment]
I updated the [README](https://github.com/obophenotype/vccf-ontology/blob/main/README.md).

Please open another ticket, if needed, to change parts of the pipeline.

**Comment by cmungall** [comment]
> How should it be translated?

Ideally the source tables would be defined at source, and then this repo would be focused on the transformation; see
https://github.com/hubmapconsortium/hra-vccf/pull/5

**Comment by anitacaron** [comment]
I was asking about the transformation.
